// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQ9nRxf6MzsXxOQH5XBoisqSrAUuHIOU',
    appId: '1:1011045085483:web:93d5693a5c939747b6156e',
    messagingSenderId: '1011045085483',
    projectId: 'actclasemobile',
    authDomain: 'actclasemobile.firebaseapp.com',
    storageBucket: 'actclasemobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVmM5cjrniGkbqTvURx8QuORg42sQx20',
    appId: '1:1011045085483:android:121232f09d9bbaefb6156e',
    messagingSenderId: '1011045085483',
    projectId: 'actclasemobile',
    storageBucket: 'actclasemobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtyxjSTdLKjfa1jGH_MbJPvlg-owRwpIE',
    appId: '1:1011045085483:ios:7c8d236d80918584b6156e',
    messagingSenderId: '1011045085483',
    projectId: 'actclasemobile',
    storageBucket: 'actclasemobile.appspot.com',
    androidClientId: '1011045085483-chmbvg9c0s7jpfi66hama5rd555qi6r0.apps.googleusercontent.com',
    iosClientId: '1011045085483-ru45md2l33clcooi042lnu2ebee30td1.apps.googleusercontent.com',
    iosBundleId: 'com.example.actQueries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtyxjSTdLKjfa1jGH_MbJPvlg-owRwpIE',
    appId: '1:1011045085483:ios:e8dc242c4896168db6156e',
    messagingSenderId: '1011045085483',
    projectId: 'actclasemobile',
    storageBucket: 'actclasemobile.appspot.com',
    androidClientId: '1011045085483-chmbvg9c0s7jpfi66hama5rd555qi6r0.apps.googleusercontent.com',
    iosClientId: '1011045085483-62j9kh7f6iu6tho0ui5p2lc2ulcn49oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.actQueries.RunnerTests',
  );
}
